import type { Metadata } from "next";
import { REM } from "next/font/google";
import "./globals.css";


import { Header } from "./components/header";
import { Footer } from "./components/footer";

const rem = REM({
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // coloca una imagen de fondo de pantalla, esta esta almacenada en la carpeta public 
        className={`${rem.className}  antialiased
        overflow-y-scroll
        bg-[url(/42.jpg)]
        bg-cover
        bg-no-repeat
        bg-fixed
        bg-top
        `}
      >

        <div className="container mt-6 mx-auto px-4">
        {/* el ancho de la pagina lo considera como una fracción max-w-9/10 */}
          <Header></Header>
            {children}
      

          <Footer/>
        
        </div>
      </body>
    </html>
  );
}
